CREATE TABLE NOTICE (
    NOTICE_ID   number(7) 		NOT NULL ,
    TITLE       varchar2(1000) 	NOT NULL ,
    CONTENT    	clob 			NOT NULL ,
    REGISTRANT 	varchar2(20) 	NOT NULL ,
    REGDATE     date 			NOT NULL ,
	PRIMARY KEY (NOTICE_ID)
);

CREATE SEQUENCE NOTICE_SEQ START WITH 1 
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE QNA(
		QNA_ID     		number(7) 		NOT NULL ,
		CATEGORY   		varchar2(20)	NOT NULL ,
		TITLE      		varchar2(1000) 	NOT NULL ,
		CONTENT    		clob 			NOT NULL ,
		REGISTRANT 		varchar2(20) 	NOT NULL ,
		REGDATE			date 			NOT NULL ,
		PRIMARY KEY (QNA_ID)
);

CREATE SEQUENCE QNA_SEQ START WITH 1 
INCREMENT BY 1
NOCACHE NOCYCLE;