CREATE TABLE USER_TABLE(	
		USER_ID 		VARCHAR2(30 BYTE)		NOT NULL ENABLE, 
		USER_NAME		VARCHAR2(20 BYTE)		NOT NULL ENABLE,
		NICKNAME 		VARCHAR2(30 BYTE) 		NOT NULL ENABLE UNIQUE, 
		USER_PWD 		VARCHAR2(200 BYTE)		NOT NULL ENABLE, 
		HP 				VARCHAR2(30 BYTE) 		NOT NULL ENABLE UNIQUE, 
		SHOESIZE 		VARCHAR2(20 BYTE) 		NOT NULL ENABLE, 
		SMS_ALLOW 		NUMBER(1,0) 			NOT NULL ENABLE, 
		EMAIL_ALLOW 	NUMBER(1,0) 			NOT NULL ENABLE, 
		PROFILE_IMG 	VARCHAR2(1000 BYTE), 
		AUTHORITY		NUMBER(2,0)				NOT NULL ENABLE,
		SIGN_UP_TYPE	VARCHAR2(20 BYTE)		NOT NULL ENABLE,
		SIGN_UP_DATE 	DATE 					NOT NULL ENABLE, 
		PRIMARY KEY (USER_ID)
);

CREATE TABLE ADDRESS (	
		ADDRESS_ID 		NUMBER(7,0) 			NOT NULL ENABLE, 
		USER_ID 		VARCHAR2(30 BYTE) 		NOT NULL ENABLE 
							REFERENCES USER_TABLE(USER_ID) ON DELETE CASCADE, 
		NAME			VARCHAR2(20 BYTE) 		NOT NULL ENABLE, 
		HP 				VARCHAR2(30 BYTE) 		NOT NULL ENABLE, 
		ZIPCODE 		VARCHAR2(20 BYTE) 		NOT NULL ENABLE, 
		ADDR 			VARCHAR2(1000 BYTE) 	NOT NULL ENABLE, 
		ADDR_DETAIL 	VARCHAR2(1000 BYTE), 
		FLAG 			NUMBER(1,0)				NOT NULL ENABLE, 
		PRIMARY KEY ("ADDRESS_ID")
		
);

CREATE SEQUENCE ADDRESS_SEQ START WITH 1 
INCREMENT BY 1
NOCACHE NOCYCLE;


